### PR TITLE
Add format:check and format. for a cleaner code base

### PR DESCRIPTION
**Pull request by kepet19**
Ready for review. 
---

### Add 
- Add **prettier** as dev packages.
- [x]  `npm run format` for formatting the project
- [x] `npm run format:check` used in CI for checking if you formatted. 

--- 

### Fix
- Fix formatting. 
- Fix lint issues
- Fix **eslint** now also checks every javascripts in components folder

### CODE REVIEW

**Review by Joergenson — APPROVED** [review]
Neat!

**Review by Joergenson — APPROVED** [review]
Nice! now I can't get commits for formatting :)

**Comment by kepet19** [comment]
> Nice! now I can't get commits for formatting :)

whoa maybe you should add a git hooks before git commits :b 
`./node_modules/.bin/prettier --check App.js components` or `npm run format:check`

**Comment by kepet19** [comment]
> > Neat!
> 
> Let's get the test app
> 
> > > Nice! now I can't get commits for formatting :)
> > 
> > 
> > whoa maybe you should add a git hooks before git commits :b `./node_modules/.bin/prettier --check App.js components` or `npm run format:check`
> 
> True rofl

I can't remember how to do it doe xD 
can you make that in a .git/config ?

**Review by Kechr — COMMENTED** [review]
Looking good!

Two questions though: 
Should we write `.js` after importing our own files, because right now we do it sometimes but not always? I saw that you added it in the `gradient-button.js` but not in the other files.

When importing, should we use curly brackets to be consistent, or only use them when importing as more than one? e.g. 
```javascript
import { LinearGradient } from "expo-linear-gradient";
import MaskedView from "@react-native-masked-view/masked-view";
import { StyleSheet, Text } from "react-native";
```

**Comment by Joergenson** [comment]
> Looking good!
> 
> Two questions though: Should we write `.js` after importing our own files, because right now we do it sometimes but not always? I saw that you added it in the `gradient-button.js` but not in the other files.
> 
> When importing, should we use curly brackets to be consistent, or only use them when importing as more than one? e.g.
> 
> ```js
> import { LinearGradient } from "expo-linear-gradient";
> import MaskedView from "@react-native-masked-view/masked-view";
> import { StyleSheet, Text } from "react-native";
> ```

Curley brackets depends on the component from react-native it is because it doesn't default export

**Comment by Joergenson** [comment]
I agree whith the .js thing it should not be included :->

**Comment by Joergenson** [comment]
> Looking good!
> 
> Two questions though: Should we write `.js` after importing our own files, because right now we do it sometimes but not always? I saw that you added it in the `gradient-button.js` but not in the other files.
> 
> When importing, should we use curly brackets to be consistent, or only use them when importing as more than one? e.g.
> 
> ```js
> import { LinearGradient } from "expo-linear-gradient";
> import MaskedView from "@react-native-masked-view/masked-view";
> import { StyleSheet, Text } from "react-native";
> ```

But forgot to refractor the imports after I redid the exports on the components so in this case, It shouldn't have curly brackets on the gradient components

**Comment by Kechr** [comment]
> > Looking good!
> > Two questions though: Should we write `.js` after importing our own files, because right now we do it sometimes but not always? I saw that you added it in the `gradient-button.js` but not in the other files.
> > When importing, should we use curly brackets to be consistent, or only use them when importing as more than one? e.g.
> > ```js
> > import { LinearGradient } from "expo-linear-gradient";
> > import MaskedView from "@react-native-masked-view/masked-view";
> > import { StyleSheet, Text } from "react-native";
> > ```
> 
> Curley brackets depend on the component. from react-native it is because it doesn't default export

Huh, havde jeg ikke lige overvejet. TIL I guess

**Comment by Joergenson** [comment]
> > > Looking good!
> > > Two questions though: Should we write `.js` after importing our own files, because right now we do it sometimes but not always? I saw that you added it in the `gradient-button.js` but not in the other files.
> > > When importing, should we use curly brackets to be consistent, or only use them when importing as more than one? e.g.
> > > ```js
> > > import { LinearGradient } from "expo-linear-gradient";
> > > import MaskedView from "@react-native-masked-view/masked-view";
> > > import { StyleSheet, Text } from "react-native";
> > > ```
> > 
> > 
> > Curley brackets depend on the component. from react-native it is because it doesn't default export
> 
> Huh, havde jeg ikke lige overvejet. TIL I guess

https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import

Det er en kunst

**Comment by Kechr** [comment]
> Just to be sure we remove all .js from import right ?

Ye

**Comment by Joergenson** [comment]
> > Just to be sure we remove all .js from import right ?
> 
> Ye

where do we have that tho cant find any?

**Comment by Joergenson** [comment]
oh nvm

**Comment by kepet19** [comment]
Right here! https://github.com/msd-d/PetHub/pull/14#issuecomment-956366090

**Review by Kechr — APPROVED** [review]

**Pull request merged**
