### PR TITLE
Database implementation

### PR DESCRIPTION
**Pull request by Joergenson**

### CODE REVIEW

**Comment by kepet19** [comment]
Nice, this is gonna be nice! :D

**Comment by Joergenson** [comment]
Yeah now all changeable data can be modified runtime and have default values we define in the dummy data :D

**Comment by kepet19** [comment]
I can see the `package-lock.json` file is revsion 1 again. God damit (me). 
Good thing I have downgrade npm, so this should not happend any more (maybe). 
We would not have big changes to `package-lock.json` 
I have both npm 6 and 8 installed, whoops my fault!.

**Review by kepet19 — APPROVED** [review]

**Comment by Joergenson** [comment]
Shiet(npm) happens :)

**Comment by kepet19** [comment]
> Shiet(npm) happens :)

haha yeah 
I have both installed with the tool `nvm` 
npm 8 is the default.

**Review by SnaBe — APPROVED** [review]
Looking great!
* However, some tabs or spaces are unaligned in the components/database.js file.

> > Looking great!
> > 
> > * However, some tabs or spaces are unaligned in the components/database.js file.
> 
> tell that to the formatted :)

That is noted, sire.

**Comment by Joergenson** [comment]
> Looking great!
> 
> * However, some tabs or spaces are unaligned in the components/database.js file.

tell that to the formatted :)

**Comment by Joergenson** [comment]
> Looking great!
> 
> * However, some tabs or spaces are unaligned in the components/database.js file.

Where tho ? 🤔

**Pull request merged**
