### PR TITLE
General styling and core functionality for animal profiles

### PR DESCRIPTION
**Pull request by SnaBe**
* Added the ability to view an animal profile posted by a given user in more detail.
  * A skeleton has been set up for the remaining elements and their styles. 
* You can now call or mail the post owner directly from the app.
* The birthDate calculation needs to be refactored to a cleaner implementation.

### CODE REVIEW

**Comment by Kechr** [comment]
> The birthDate calculation needs to be refactored to a cleaner implementation   

Is this a new issue?

**Comment by SnaBe** [comment]
> > The birthDate calculation needs to be refactored to a cleaner implementation
> 
> Is this a new issue?

It was, but has been fixed by a [commit](https://github.com/msd-d/PetHub/pull/66/commits/4f39ac22541263b5b1d1b1403f9ebc93be92d446).

**Review by Kechr — COMMENTED** [review]
Looking good! But, should we not include the breed on the animal profile?
image
image

Also, the buttons for phone and email are ellipses, and not circles (on my screen at least)
image

**Comment by SnaBe** [comment]
> Looking good! But, should we not include the breed on the animal profile? image image
> 
> Also, the buttons for phone and email are ellipses, and not circles (on my screen at least) image

Of course, I just decided to commit and make a PR with the work I got done in class, as I won’t be by my computer for the rest of the at. Feel free to mark it as a draft or pull and commit directly.

**Comment by Joergenson** [comment]
Screenshot_1636830410
Looking at the options; just use the icon with the darkgrey or pethubpink color

**Comment by SnaBe** [comment]
> Screenshot_1636830410
> Looking at the options; just use the icon with the darkgrey or pethubpink color

Not sure what you mean, do you want me to replicate your design? Or change the color?

**Comment by Joergenson** [comment]
> > Screenshot_1636830410
> > Looking at the options; just use the icon with the darkgrey or pethubpink color
> 
> Not sure what you mean, do you want me to replicate your design? Or change the color?

I mean just use the icon. not buttons. 

```
<TouchableOpacity
  onpress={owo}
>
   <Icon>
</TouchableOpacity>
```

**Comment by SnaBe** [comment]
> > > Screenshot_1636830410
> > > Looking at the options; just use the icon with the darkgrey or pethubpink color
> > 
> > 
> > Not sure what you mean, do you want me to replicate your design? Or change the color?
> 
> I mean just use the icon. not buttons.
> 
> ```
> <TouchableOpacity
>   onpress={owo}
> >
>    <Icon>
> </TouchableOpacity>
> ```

Ah got you, I'll get that done no worries.

**Review by kepet19 — APPROVED** [review]

**Pull request merged**
